name: Update Thresholds

on:
  repository_dispatch:
    types: [update-thresholds]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update CSV file
        run: |
          echo "TempMin,TempMax,HumMin,HumMax" > thresholds.csv
          echo "${{ github.event.client_payload.tempMin }},${{ github.event.client_payload.tempMax }},${{ github.event.client_payload.humMin }},${{ github.event.client_payload.humMax }}" >> thresholds.csv

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add thresholds.csv
          git commit -m "Updated thresholds via GitHub Actions"
          git push
