name: Update thresholds

on:
  workflow_dispatch:
    inputs:
      tmin:
        description: 'Temperature Min'
        required: true
      tmax:
        description: 'Temperature Max'
        required: true
      hmin:
        description: 'Humidity Min'
        required: true
      hmax:
        description: 'Humidity Max'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update thresholds.csv
        run: |
          echo "TempMin,TempMax,HumMin,HumMax" > thresholds.csv
          echo "${{ github.event.inputs.tmin }},${{ github.event.inputs.tmax }},${{ github.event.inputs.hmin }},${{ github.event.inputs.hmax }}" >> thresholds.csv

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add thresholds.csv
          git commit -m "Update thresholds.csv from workflow"
          git push
